title: psy_world blog
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Start psy_world blog

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed
